### ISSUE TITLE
error: can't create transaction lock on

### ISSUE THREAD

**Issue by dtometzki** [chainsx/fedora-riscv-builder#1]
Hello together,

the command rpm --root  $WORKDIR/rootfs/ --initdb doesnt work on any fedora 38 system. 

Is there anything todo ?

```
[damian@fedora misc]$ WORKDIR=$(pwd)
[damian@fedora misc]$ cd $WORKDIR
[damian@fedora misc]$ mkdir rootfs
mkdir: cannot create directory ‘rootfs’: File exists
[damian@fedora misc]$ mkdir -p rootfs/var/lib/rpm
[damian@fedora misc]$ rpm --root  $WORKDIR/rootfs/ --initdb
error: can't create transaction lock on /home/damian/kernel/misc/rootfs/usr/lib/sysimage/rpm/.rpm.lock (Permission denied)
[damian@fedora misc]$ sudo rpm --root  $WORKDIR/rootfs/ --initdb
error: can't create transaction lock on /home/damian/kernel/misc/rootfs/usr/lib/sysimage/rpm/.rpm.lock (Permission denied)
[damian@fedora misc]$ 
[damian@fedora misc]$ 
[damian@fedora misc]$ 
```

**Comment by chainsx** [comment]
You may need to delete the existing `rootfs` directory and follow the instructions in the new [README](https://github.com/chainsx/fedora-riscv-builder/blob/main/README.en.md) for further operations.

**Comment by dtometzki** [comment]
Hello,

sorry but it doesnt work

[damian@fedora ~]$ rpm --root  $WORKDIR/rootfs/ --initdb
error: can't create transaction lock on /home/damian/rootfs/usr/lib/sysimage/rpm/.rpm.lock (Permission denied)
[damian@fedora ~]$ ll -a /var/lib/rpm/
total 0
drwxr-xr-x. 1 root root 0 Jun 11 19:20 .
drwxr-xr-x. 1 root root 6 Jan 19 01:00 ..
[damian@fedora ~]$

**Comment by chainsx** [comment]
Um, what I mean is, you should switch to the root user first, try performing the subsequent operations in the terminal after seeing the "#" symbol?

**Comment by dtometzki** [comment]
Hello,
i think it has anything with security to do. Curiose is under /tmp command works but on other dir doesnt work

```
[root@fedora ~]# rpm --root=/tmp --initdb 
[root@fedora ~]# rpm --root=/home --initdb 
error: can't create transaction lock on /home/usr/lib/sysimage/rpm/.rpm.lock (No such file or directory)
[root@fedora ~]# 
```

**Comment by chainsx** [comment]
> No such file or directory

I guess the error "No such file or directory" in initdb under the /home folder is because the intermediate folder hasn't been created.

**Comment by dtometzki** [comment]
Hello,

these is an Selinux issue. I could resolve temp. the issue:

sudo setenforce 0
do rpm ....

sudo setenforce 1

**Comment by chainsx** [comment]
Thank you for your feedback. Actually, I didn't take into account the issue with SELinux.
