### ISSUE TITLE
Build  doesnt work

### ISSUE THREAD

**Issue by dtometzki** [chainsx/fedora-riscv-builder#3]
Hello,

I have done the following steps with the release

sudo ./fastboot flash boot boot.img
sudo ./fastboot flash root root.img

But after restart the old OS is up and runing

[damian@fedora tempfix0428]$ sudo ../tools/linux/fastboot flash boot /home/damian/Downloads/boot.img 
Invalid sparse file format at header magic
Sending sparse 'boot' 1/13 (1148 KB)               OKAY [  0.303s]
Writing 'boot'                                     OKAY [  0.002s]
Sending sparse 'boot' 2/13 (1148 KB)               OKAY [  0.303s]
Writing 'boot'                                     OKAY [  0.002s]
Sending sparse 'boot' 3/13 (1148 KB)               OKAY [  0.303s]
Writing 'boot'                                     OKAY [  0.002s]
Sending sparse 'boot' 4/13 (1148 KB)               OKAY [  0.303s]
Writing 'boot'                                     OKAY [  0.002s]
Sending sparse 'boot' 5/13 (1148 KB)               OKAY [  0.303s]
Writing 'boot'                                     OKAY [  0.002s]
Sending sparse 'boot' 6/13 (1148 KB)               OKAY [  0.304s]
Writing 'boot'                                     OKAY [  0.002s]
Sending sparse 'boot' 7/13 (1148 KB)               OKAY [  0.303s]
Writing 'boot'                                     OKAY [  0.002s]
Sending sparse 'boot' 8/13 (1148 KB)               OKAY [  0.304s]
Writing 'boot'                                     OKAY [  0.002s]
Sending sparse 'boot' 9/13 (1148 KB)               OKAY [  0.304s]
Writing 'boot'                                     OKAY [  0.002s]
Sending sparse 'boot' 10/13 (1148 KB)              OKAY [  0.304s]
Writing 'boot'                                     OKAY [  0.002s]
Sending sparse 'boot' 11/13 (1148 KB)              OKAY [  0.305s]
Writing 'boot'                                     OKAY [  0.002s]
Sending sparse 'boot' 12/13 (1148 KB)              OKAY [  0.305s]
Writing 'boot'                                     OKAY [  0.002s]
Sending sparse 'boot' 13/13 (564 KB)               OKAY [  0.153s]
Writing 'boot'                                     OKAY [  0.002s]
Finished. Total time: 3.898s
[damian@fedora tempfix0428]$ 

..
..
Sending sparse 'root' 1008/1014 (1148 KB)          OKAY [  0.304s]
Writing 'root'                                     OKAY [  0.002s]
Sending sparse 'root' 1009/1014 (1148 KB)          OKAY [  0.305s]
Writing 'root'                                     OKAY [  0.002s]
Sending sparse 'root' 1010/1014 (1148 KB)          OKAY [  0.304s]
Writing 'root'                                     OKAY [  0.002s]
Sending sparse 'root' 1011/1014 (1148 KB)          OKAY [  0.304s]
Writing 'root'                                     OKAY [  0.002s]
Sending sparse 'root' 1012/1014 (1148 KB)          OKAY [  0.303s]
Writing 'root'                                     OKAY [  0.002s]
Sending sparse 'root' 1013/1014 (1148 KB)          OKAY [  0.305s]
Writing 'root'                                     OKAY [  0.002s]
Sending sparse 'root' 1014/1014 (1016 KB)          OKAY [  0.270s]
Writing 'root'                                     OKAY [  0.002s]
Finished. Total time: 310.317s

**Comment by chainsx** [comment]
Currently, support for EMMC booting is unstable. You can refer to the [Installing System to SD Card](https://github.com/chainsx/fedora-riscv-builder/blob/main/doc/install-guild-licheepi4a.md#installing-system-to-sd-card) section  to use the system from the SD card.

**Comment by dtometzki** [comment]
I dont understand it. Because fastboot finished without any error. I dont where are the data ?

**Comment by chainsx** [comment]
I also don't know what the situation is with your device.

**Comment by dtometzki** [comment]
Hello,

i found my mistake. you always have to do the steps in advance: 
Always first the offical u-boot-with-spl.bin then boot.img and root.img as described on the wiki site. 

Fedora is booting but wifi and isnt working

**Comment by dtometzki** [comment]
Hello,

the fedora image is booting fine. But the extend of the root filesystem breaks the root partition. And then a reboot faild because of root partition. I removed the script now it works. 

Network Wifi doesnt work. I copied /lib/firmware but without success. 

So that ist my actual status

**Comment by chainsx** [comment]
I'm sorry for taking so long to reply to your issue, but unfortunately, the information and documentation provided by T-Head are not yet complete. Additionally, we need to consider compatibility with the system installation method specified by [Revyos](https://github.com/revyos), which makes it difficult to know where to start. When the official version of LicheePi 4A is released, some relevant documents may be provided, and at that time, I will update this project.

**Comment by chainsx** [comment]
@dtometzki 
I saw someone in the official QQ group of Sipeed encountering a similar issue while flashing the official system. The official response to this is as follows: By long-pressing the BOOT button and powering on, you can enter the fastboot mode, but it only allows you to flash files to the RAM, not the actual storage. Therefore, you should connect the development board via a serial port and input "fastboot usb 0" in the serial console to proceed with the system flashing.
