### ISSUE TITLE
WIFI doesnt work with new release

### ISSUE THREAD

**Issue by dtometzki** [chainsx/fedora-riscv-builder#4]
Hi,
on my site wifi doesnt work:

[root@fedora-riscv ~]# nmcli dev status
DEVICE  TYPE      STATE                   CONNECTION 
lo      loopback  connected (externally)  lo         
end0    ethernet  unavailable             --         
end1    ethernet  unavailable             --         
sit0    iptunnel  unmanaged               --         
p2p0    wifi      unmanaged               --         
wlan0   wifi      unmanaged               --

**Comment by chainsx** [comment]
The WiFi functionality seems to be fine, and indeed, it was working when I tested it. However, you might need to configure NetworkManager to take over the wlan0 interface?

**Comment by dtometzki** [comment]
Hello,

could you please add the follwing package to the image ?
dnf install NetworkManager-wifi NetworkManager-wwan

the it is possible to install wifi with nmcli

And fedora works with the emmc

**Comment by chainsx** [comment]
> Hello,
> 
> could you please add the follwing package to the image ? dnf install NetworkManager-wifi NetworkManager-wwan
> 
> the it is possible to install wifi with nmcli
> 
> And fedora works with the emmc

ok

**Comment by dtometzki** [comment]
> > Hello,
> > could you please add the follwing package to the image ? dnf install NetworkManager-wifi NetworkManager-wwan
> > the it is possible to install wifi with nmcli
> > And fedora works with the emmc
> 
> ok

Hello chainsx,

i thing with this you can generate the emmc images with the origin u-boot and dts. Then you have an initial ready to run fedora image with eth and wifi. What i see usb works too. 

What do you mean ?
Great and many thanks
Damian

**Comment by chainsx** [comment]
Thank you for your suggestion. I have already applied your suggestion, but after testing, it turns out that the NetworkManager-wwan package is unnecessary and it prints errors during boot-up.

**Comment by chainsx** [comment]
Nice to meet you! I see that you are very interested in this project.
I am a college student from China, and I am currently preparing for my postgraduate exams. I pursue these hobbies in my limited free time, so I may not be able to respond to your messages promptly. I apologize for any inconvenience caused and appreciate your understanding.
